defmodule Postern.Catalog do
  @moduledoc """
  Loads generated PostgreSQL setting catalogs.

  Catalog files are generated by `mix postern.catalog` from live
  `pg_settings` rows. This module does not contain PostgreSQL setting
  metadata in source code.
  """

  @required_fields ~w(name vartype unit context category short_desc extra_desc min_val max_val enumvals boot_val reset_val)

  @doc """
  Loads the catalog for a PostgreSQL major version.

  The returned map contains the version and settings indexed by setting name.
  A row's `enumvals` is a list, decoded here when a catalog holds the array
  literal the text protocol delivers, and an enum row's `hidden_enumvals`
  maps each spelling the server takes without listing it to the visible
  value it stands for. The catalog also carries the time zone names the
  server knows, its encodings, and the aliases of those.
  """
  @spec load(pos_integer(), keyword()) :: %{
          version: pos_integer(),
          settings: map(),
          timezones: [String.t()],
          encodings: [String.t()],
          encoding_aliases: [String.t()]
        }
  def load(version, opts \\ []) when is_integer(version) do
    path = Path.join(catalog_dir(opts), "pg#{version}.json")

    with {:ok, json} <- File.read(path),
         {:ok, %{"settings" => settings} = catalog} <- Jason.decode(json) do
      %{
        version: version,
        settings: Map.new(settings, &{Map.fetch!(&1, "name"), with_enum_list(&1)}),
        timezones: Map.get(catalog, "timezones", []),
        encodings: Map.get(catalog, "encodings", []),
        encoding_aliases: Map.get(catalog, "encoding_aliases", [])
      }
    else
      {:error, reason} ->
        raise "unable to load PostgreSQL #{version} catalog at #{path}: #{:file.format_error(reason)}"

      {:ok, other} ->
        raise "invalid PostgreSQL #{version} catalog at #{path}: #{inspect(other)}"
    end
  end

  @doc "Returns the PostgreSQL major versions whose catalogs are present."
  @spec versions(keyword()) :: [pos_integer()]
  def versions(opts \\ []) do
    catalog_dir(opts)
    |> Path.join("pg*.json")
    |> Path.wildcard()
    |> Enum.map(&Path.basename(&1, ".json"))
    |> Enum.flat_map(fn "pg" <> version -> parse_version(version) end)
    |> Enum.sort()
  end

  @doc "Returns the newest generated catalog version."
  @spec latest(keyword()) :: pos_integer()
  def latest(opts \\ []) do
    case versions(opts) do
      [] -> raise "no PostgreSQL catalogs found in #{catalog_dir(opts)}"
      versions -> List.last(versions)
    end
  end

  @doc "Fetches one setting row from a loaded catalog."
  @spec fetch(%{settings: map()}, String.t()) :: map() | nil
  def fetch(%{settings: settings}, name) do
    Map.get(settings, name) ||
      Enum.find_value(settings, fn {candidate, setting} ->
        if String.downcase(candidate) == String.downcase(name), do: setting
      end)
  end

  @doc "Returns the source field names expected in every generated setting row."
  @spec required_fields() :: [String.t()]
  def required_fields, do: @required_fields

  @doc """
  The elements of a PostgreSQL array literal, as `array_out` prints one.

  An element is double-quoted when it holds a comma, a brace, a quote, a
  backslash or white space, or is empty, and inside the quotes a backslash
  escapes the next character. A list is returned as it is, and anything else
  is no elements.

  ## Examples

      iex> Postern.Catalog.array_literal(~s({serializable,"repeatable read","read committed"}))
      ["serializable", "repeatable read", "read committed"]

      iex> Postern.Catalog.array_literal(~S({"a\\"b","c\\\\d",""}))
      [~S(a"b), ~S(c\\d), ""]

      iex> Postern.Catalog.array_literal("{}")
      []

  """
  @spec array_literal(String.t() | [String.t()] | nil) :: [String.t()]
  def array_literal(list) when is_list(list), do: list

  def array_literal("{" <> rest) do
    rest
    |> String.trim_trailing("}")
    |> elements([], "", false)
  end

  def array_literal(_other), do: []

  defp with_enum_list(setting) do
    setting
    |> Map.update("enumvals", nil, &enum_list/1)
    |> Map.put_new("hidden_enumvals", if(setting["vartype"] == "enum", do: %{}, else: nil))
    |> Map.put_new("module", nil)
  end

  @doc "The modules whose settings a catalog knows, from the prefix before the dot."
  @spec modules(%{settings: map()}) :: [String.t()]
  def modules(%{settings: settings}) do
    settings
    |> Enum.map(fn {_name, setting} -> setting["module"] end)
    |> Enum.reject(&is_nil/1)
    |> Enum.uniq()
    |> Enum.sort()
  end

  defp enum_list(nil), do: nil
  defp enum_list(values), do: array_literal(values)

  # The elements so far, the one being read, and whether the reader has
  # just closed a quoted element, after which only a comma or the end may
  # follow. A quoted element may be empty, so the quotes themselves mark
  # that an element was read.
  defp elements("", acc, current, _closed), do: finish(acc, current)

  defp elements(<<?", rest::binary>>, acc, current, false), do: quoted(rest, acc, current)

  defp elements(<<?,, rest::binary>>, acc, current, _closed),
    do: elements(rest, [current | acc], "", false)

  defp elements(<<char::utf8, rest::binary>>, acc, current, false),
    do: elements(rest, acc, current <> <<char::utf8>>, false)

  defp elements(_rest, acc, current, true), do: finish(acc, current)

  defp quoted(<<?\\, char::utf8, rest::binary>>, acc, current),
    do: quoted(rest, acc, current <> <<char::utf8>>)

  defp quoted(<<?", rest::binary>>, acc, current), do: elements(rest, acc, current, true)

  defp quoted(<<char::utf8, rest::binary>>, acc, current),
    do: quoted(rest, acc, current <> <<char::utf8>>)

  defp quoted("", acc, current), do: finish(acc, current)

  defp finish([], ""), do: []
  defp finish(acc, current), do: Enum.reverse([current | acc])

  defp catalog_dir(opts) do
    Keyword.get(opts, :catalog_dir, Path.join(:code.priv_dir(:postern), "catalog"))
  end

  defp parse_version(version) do
    case Integer.parse(version) do
      {number, ""} -> [number]
      _ -> []
    end
  end
end
